version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '8080:3000'
      - '5173:5173'
    volumes:
      - ./server:/usr/src/app/server
      - ./shared:/usr/src/app/shared
      - ./client:/usr/src/app/client
    depends_on:
      - db


  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: image-game


  dbadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: pgadmin4